### ISSUE TITLE
JxlEncoderProcessOutput returned JXL_ENC_ERROR when handling some images

### ISSUE THREAD

**Issue by zhou13** [cgohlke/imagecodecs#71] opened 2023-04-05 19:40 UTC
To reproduce the error, use:
```python
import numpy as np
from imagecodecs import imwrite

buffer = np.load("1.npy")
print(buffer.shape, buffer.dtype)
imwrite("1.jxl", buffer)
```
Here is the example buffer:
[1.npy.zip](https://github.com/cgohlke/imagecodecs/files/11162460/1.npy.zip)

I got error
```
(1536, 1536) float32
Traceback (most recent call last):
  File "reproduce.py", line 6, in <module>
    imwrite("1.jxl", buffer)
  File "/miniconda/envs/main/lib/python3.8/site-packages/imagecodecs/imagecodecs.py", line 1399, in imwrite
    image: bytes = codec(data, **kwargs)
  File "imagecodecs\_jpegxl.pyx", line 561, in imagecodecs._jpegxl.jpegxl_encode
imagecodecs._jpegxl.JpegxlError: JxlEncoderProcessOutput returned JXL_ENC_ERROR
```

The error seems to be size related rather than content-related: If I slice the buffer to be smaller, or if I do `imwrite("1.jxl", np.float32(buffer.astype(np.float16)))`, the error will go away.  The region I slice does not matter too much.

It would be helpful to print the error from `JxlEncoderGetError` so we can know what the error is.

**Comment by cgohlke** [comment] 2023-04-08 00:24
Looks like a bug/limitation in libjxl. Try other encoding parameters (e.g. lossy mode with `level=99`) or use your workaround until the issue is fixed in a future version of libjxl.

> It would be helpful to print the error from JxlEncoderGetError so we can know what the error is.

That's on the [TODO list](https://github.com/cgohlke/imagecodecs/blob/a74e4f305a9c8c317da17beb7a0698543c27b4ae/imagecodecs/_jpegxl.pyx#L99) but would not help in this case as `JxlEncoderGetError` just returns `JXL_ENC_ERR_GENERIC`.

**Closed by cgohlke** 2023-04-08 00:24 UTC
