### ISSUE TITLE
PYPI package for arm64 OSX

### ISSUE THREAD

**Issue by ilya-lavrenov** [cgohlke/imagecodecs#48] opened 2022-09-25 17:10 UTC
Could you please provide OSX arm64 package for PyPI?
It's unreal to build it from sources because of huge number of dependencies. 
I would assume that source pypi package must contain all dependencies internally, because I've tried to build pypi package and gave up with this on 6th dependency.

**Comment by ilya-lavrenov** [comment] 2022-09-25 17:26
Looks like such request is asked already https://github.com/cgohlke/imagecodecs/issues/44
How can we help with build instructions for OSX arm64? do you know specific places which need to be fixed?

**Comment by cgohlke** [comment] 2022-09-25 19:11
Duplicate of #44. See also https://github.com/Czaki/imagecodecs_build/issues/2.

Imagecodecs binaries are available for osx-arm64 on [MacPorts](https://ports.macports.org/port/py-imagecodecs/details/) and [conda-forge](https://anaconda.org/conda-forge/imagecodecs). 

Imagecodecs allows to build with missing dependencies via the `--lite`  or `--skip-extension` build options.

The imagecodecs build scripts are unable to build wheels for osx-arm64 because that platform is [still not available on Azure Pipelines](https://github.com/microsoft/azure-pipelines-agent/issues/3184).

**Closed by cgohlke** 2022-09-25 19:11 UTC
Labels: duplicate, question

**Comment by alanwilter** [comment] 2023-01-01 19:20
There's a pre-release for Azure pipeline that contains macOS Arm64.
https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.214.0
