### ISSUE TITLE
Failing to build manylinux2014 AArch64 wheels 

### ISSUE THREAD

**Issue by odidev** [cgohlke/imagecodecs#24] opened 2021-10-01 05:32 UTC
On AArch64 machine, ```pip installl imagecodecs``` tries to build the wheels from source code and fails with below error-

```
    /opt/_internal/cpython-3.8.12/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
    imagecodecs/_blosc2.c:627:10: fatal error: blosc2.h: No such file or directory
      627 | #include "blosc2.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

@cgohlke, can you please let me know your interest in deploying AArch64 wheels on PyPI? Can you please point out your wheel builder? I would like to help in this.

**Comment by cgohlke** [comment] 2021-10-01 15:20
Looks like you have `LD_LIBRARY_PATH` or `LIBRARY_PATH` defined in your environment. Please confirm. Otherwise blosc2 would not be required.

Please see the [Requirements](https://github.com/cgohlke/imagecodecs#requirements) and [Notes](https://github.com/cgohlke/imagecodecs#notes) for building from source. The Linux and macOS wheels are built based on @Czaki
https://github.com/Czaki/imagecodecs_build repro so you may want to contribute there.

**Comment by Czaki** [comment] 2021-10-01 15:38
The tool which I use for build wheels (`cibuildwheel`) support now aarch64.
I do not have access to aarh64 machine so I'm fully open on cooperation to add its support with someone with such hardware acces.

**Comment by cgohlke** [comment] 2021-10-01 15:46
Thanks @Czaki . Somewhat related to this issue: do you know the status of Apple silicon in cibuildwheel and Azure Pipelines?

**Comment by Czaki** [comment] 2021-10-01 15:58
Also supported. Also lack of access to hardware. I could try to enable but macos 11.0 introduce some changes in security mechanism, which breaks build process. With cooperation of one person I start fixing it but to finish it in a relatively short time there is a need to have access to m1 hardware.
(Building double architecture libraries).

Or maybe simpler it will be to build pure arm wheels, not universal2 ones.

**Comment by cgohlke** [comment] 2021-10-01 16:59
> Looks like you have `LD_LIBRARY_PATH` or `LIBRARY_PATH` defined in your environment. Please confirm. Otherwise blosc2 would not be required.

https://github.com/cgohlke/imagecodecs/blob/8eec683f117b44c178785f542831f530511608ff/setup.py#L509-L510

It's probably better to define a `IMAGECODECS_BUILD` environment variable in the CI and use that instead of `LD_LIBRARY_PATH` or `LIBRARY_PATH`.

**Comment by Czaki** [comment] 2021-10-01 17:27
> It's probably better to define a `IMAGECODECS_BUILD` environment variable in the CI and use that instead of `LD_LIBRARY_PATH` or `LIBRARY_PATH`.

Agree. I will switch. 

I prefer to wait for https://github.com/pypa/cibuildwheel/pull/854 to be merged and then move the configuration to `pyproject.toml` which will simplify live and allow easier select CI provider.

**Comment by cgohlke** [comment] 2021-10-01 17:33
I had only bad experiences with `pyproject.toml` and many of my build scripts start with `del pyproject.toml`...

**Comment by henryiii** [comment] 2021-10-01 17:57
You can use cibuildwheel.toml and `--config=cibuildwheel.toml` then. Though I would recommend trying to learn what it actually does and you'll find it's fantastic and solves important problems. Also, don't delete pyproject.toml, just use `--no-build-isolation` or `PIP_NO_BUILD_ISOLATION=<x>` (never remember how you set a "no" variable in Pip, other than it's weird and backward. Maybe 0 or off or something like that).

**Comment by henryiii** [comment] 2021-10-01 17:59
I have also had problems with pyproject.toml, but the problem is always that they are missing from some dependencies. ;)

**Comment by Czaki** [comment] 2021-10-01 19:27
I was thinking to move the configuration to any toml file. Building aarch64 is supported by emulation it consumes a long time so it may be nice to move some of the work on GitHub actions.

**Closed** 2021-10-03 03:25 UTC

**Comment by odidev** [comment] 2021-10-04 05:35
@Czaki, How about using CircleCI to build aarch64 wheels? CircleCI provides free AArch64 build agent.

**Comment by Czaki** [comment] 2021-10-04 06:02
I will try

**Comment by cgohlke** [comment] 2023-12-31 05:16
The v2024.1.1 release includes manylinux_aarch64 wheels.
