### ISSUE TITLE
OSX/ARM wheel missing

### ISSUE THREAD

**Issue by martindurant** [cgohlke/imagecodecs#72] opened 2023-04-12 17:14 UTC
https://pypi.org/project/imagecodecs/#files

I see wheels for 
- pypy
- cpython
  - win(32,arm64,x64)
  - manylinux
  - osx/x64 
  
but no osx/arm.

Related: https://github.com/conda-forge/imagecodecs-feedstock/pull/79

**Comment by cgohlke** [comment] 2023-04-12 17:26
Duplicate of #44, #48, and #70. I have ordered the "cheapest" m2 mac mini but apparently it'll take months to deliver...

**Closed by cgohlke** 2023-04-12 17:26 UTC

**Comment by martindurant** [comment] 2023-04-12 17:32
Also, I am happy to be your build farm, if we can work out a reasonable way to organise this. I think that for most of the xarray user base, conda-forge would be the preferred solution.

**Comment by cgohlke** [comment] 2023-04-13 14:12
> I'll give github actions a try

Exceeded GitHub storage quota after three failed runs :( 

Numcodecs and several other testing dependencies do not provide macos_x86_64 wheels.

**Comment by cgohlke** [comment] 2023-04-13 15:09
> Although that does not build for pypy and doesn't need to build a load of upstream dependencies on the fly, maybe that's the difference. 

Downloading and building all the dependencies takes most resources. It hasn't even gotten to building any wheels or test dependencies.

> I didn't realize about numcodecs - also a build system that hasn't been updated recently. I had not noticed because of conda-forge.

There's now a [PR](https://github.com/zarr-developers/numcodecs/pull/428) for that.

**Comment by cgohlke** [comment] 2023-04-14 20:18
Porting from Azure to GitHub Actions was straightforward and the pipeline (without testing) finishes without errors on macos-latest-arm64. However, the produced wheels are unusable. It looks like the required libraries are built for x86_64 instead of arm64 by default on that platform and linking them to arm64 Python extension produces no error, neither does delocating the extensions. Given that none of the imagecodecs dependencies currently have working CI builds for macos-arm64, I'll postpone this issue to a time the platform is properly supported.

**Comment by cgohlke** [comment] 2023-04-19 04:10
I uploaded experimental `macosx_11_0_arm64` wheels for CPython 3.10 and 3.11 to PyPI. Unfortunately the project reached its storage limit and I'll have to start removing old releases...

**Comment by martindurant** [comment] 2023-04-20 00:39
Sorry this process turned out painful!
