### ISSUE TITLE
Mac OS installation error 

### ISSUE THREAD

**Issue by henrykironde** [cgohlke/imagecodecs#17] opened 2021-05-25 04:46 UTC
Looks like there may be an error in the latest release. 

The Deep forest pytorch  package uses this tool and it seems like it fails on MacOS
https://github.com/weecology/DeepForest-pytorch/pull/69/checks?check_run_id=2661273045#step:4:1068

**Comment by cgohlke** [comment] 2021-05-26 18:57
This is a duplicate of #6. The macOS wheels are built over at https://github.com/Czaki/imagecodecs_build. "Delocating" the wheels is currently failing. No workaround/fix has been found yet. 

Try `pip install imagecodecs==2021.4.28`

**Closed by cgohlke** 2021-05-26 18:57 UTC
